apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: devops
type: Opaque
data:
  MONGO_ROOT_USERNAME: bW9uZ29hZG1pbg==  # Base64 encoded
  MONGO_ROOT_PASSWORD: c2VjdXJlUGFzcw==  # Base64 encoded
